### ISSUE TITLE
Status of the hardrive code

### ISSUE THREAD

**Issue by emoon** [mras0/AmiEmu#2]
Hi,

I'm thinking about using the hardrive code in a project of mine. The idea is to allow users to have read-only access to a image and there is no emulation involved (i.e it should be able to locate directories and files in the image and read data)

So I'm just wonder what the state of the current code is? As I don't need to support any emulation (i.e DOS calls) I can likely simplify the code a bit as well. I know that you helped out with the HDD support for vAmiga, but I'm unsure if any changes were made, etc.

**Comment by mras0** [comment]
My only contribution was the diag (expansion) ROM that adds a device (driver) once emulation is up and running (and some technical support getting that to work), so for your use case that's not relevant.

Using the vAmiga code, you should be able to create a `HDFFile` instance with the filename as a parameter, and then access the underlying data using the `FileSystem` class. You can query the HDFFile for a list of partitions using getPartitionDescriptors (there'll only be one unless it's a RDB image). That should work for OFS and FFS disks alike ("alien" filesystems like PFS3 would require emulation or extra support that's unlikely to come).

The interface looks a bit lowlevel to me, so you probably want to create some helper functions that do what you need. `FileSystem::printDirectory` looks like a good starting point. Maybe there's an easier way, but you'd have to ask the expert.

**Comment by emoon** [comment]
I see.

So you don't recommend that I use the code in this repo then?

**Comment by mras0** [comment]
Depends on what you're looking for. Something like [Adflib](https://github.com/lclevy/ADFlib) was made to handle your use case (in addition to a bunch of other stuff).  The vAmiga code probably handles more edge cases. The code in this repo is mostly a testbed for my own experiments, though I try to keep the code quality somewhat reasonable :).

If you only need to support read-only OFS/FFS non-RDB HDFs you should be able to quickly adapt the code in adf.cpp for your needs (it currently has some sanity checks that assumes a standard DD-disk and has hardcoded the root block sector), but otherwise should work fine. Adding RDB support with the stuff in harddisk.cpp shouldn't be that hard either, I just haven't done that.

Reading from OFS/FSS disk images isn't that difficult (a non-RDB HDF file is just a large ADF file).

I guess what I'm trying to say is: If you have a fairly narrow use case and want just want to integrate a small piece of code (STB style) I'll help out and the code in this repo is useful, otherwise go for something else :)

**Comment by dirkwhoffmann** [comment]
> My only contribution was the diag (expansion) ROM

"Only" is clearly an understatement 😉. The ROM is essentially the main thing.

Regarding the vAmiga code, @mras0 explained it perfectly well. You could create an `HDFFile` object and convert it to a `FileSystem` object. The `FileSystem`class has some API functions for reading files and directories. `MutableFileSystem` extends `FileSystem` with some API functions for creating files and directories.

**Comment by emoon** [comment]
Alright. Thanks for the info :)
